language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper.*$/
script:
  - yarn
  - yarn build
  - yarn coverage --reporters=default --maxWorkers=2
  - npm install -g codacy-coverage && cat ./coverage/lcov.info | codacy-coverage
  - npm install -g coveralls && cat ./coverage/lcov.info | coveralls
