name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  node-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn
    - run: yarn commitlint-circle
    - run: yarn lint
    - run: yarn build
    - run: yarn depcheck
    - run: yarn coverage --maxWorkers=2
    - run: yarn codecov
    - run: echo release
      if: github.event_name == 'push'
  node-others:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - run: yarn coverage --maxWorkers=2
